// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
        LoginPage: typeof import('./src/components/LoginPage.vue')['default'];
        MainPage: typeof import('./src/components/MainPage.vue')['default'];
        Message: typeof import('./src/components/Message/Message.vue')['default'];
    }
}

export {};
